# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.22

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/particle/Documents/DS2_Final_Project

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/particle/Documents/DS2_Final_Project

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/particle/Documents/DS2_Final_Project/CMakeFiles /home/particle/Documents/DS2_Final_Project//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/particle/Documents/DS2_Final_Project/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named CartPoleRL

# Build rule for target.
CartPoleRL: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 CartPoleRL
.PHONY : CartPoleRL

# fast build rule for target.
CartPoleRL/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CartPoleRL.dir/build.make CMakeFiles/CartPoleRL.dir/build
.PHONY : CartPoleRL/fast

src/CartPoleSimulation.o: src/CartPoleSimulation.cpp.o
.PHONY : src/CartPoleSimulation.o

# target to build an object file
src/CartPoleSimulation.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CartPoleRL.dir/build.make CMakeFiles/CartPoleRL.dir/src/CartPoleSimulation.cpp.o
.PHONY : src/CartPoleSimulation.cpp.o

src/CartPoleSimulation.i: src/CartPoleSimulation.cpp.i
.PHONY : src/CartPoleSimulation.i

# target to preprocess a source file
src/CartPoleSimulation.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CartPoleRL.dir/build.make CMakeFiles/CartPoleRL.dir/src/CartPoleSimulation.cpp.i
.PHONY : src/CartPoleSimulation.cpp.i

src/CartPoleSimulation.s: src/CartPoleSimulation.cpp.s
.PHONY : src/CartPoleSimulation.s

# target to generate assembly for a file
src/CartPoleSimulation.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CartPoleRL.dir/build.make CMakeFiles/CartPoleRL.dir/src/CartPoleSimulation.cpp.s
.PHONY : src/CartPoleSimulation.cpp.s

src/PhysicsSystem.o: src/PhysicsSystem.cpp.o
.PHONY : src/PhysicsSystem.o

# target to build an object file
src/PhysicsSystem.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CartPoleRL.dir/build.make CMakeFiles/CartPoleRL.dir/src/PhysicsSystem.cpp.o
.PHONY : src/PhysicsSystem.cpp.o

src/PhysicsSystem.i: src/PhysicsSystem.cpp.i
.PHONY : src/PhysicsSystem.i

# target to preprocess a source file
src/PhysicsSystem.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CartPoleRL.dir/build.make CMakeFiles/CartPoleRL.dir/src/PhysicsSystem.cpp.i
.PHONY : src/PhysicsSystem.cpp.i

src/PhysicsSystem.s: src/PhysicsSystem.cpp.s
.PHONY : src/PhysicsSystem.s

# target to generate assembly for a file
src/PhysicsSystem.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CartPoleRL.dir/build.make CMakeFiles/CartPoleRL.dir/src/PhysicsSystem.cpp.s
.PHONY : src/PhysicsSystem.cpp.s

src/RLTrainer.o: src/RLTrainer.cpp.o
.PHONY : src/RLTrainer.o

# target to build an object file
src/RLTrainer.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CartPoleRL.dir/build.make CMakeFiles/CartPoleRL.dir/src/RLTrainer.cpp.o
.PHONY : src/RLTrainer.cpp.o

src/RLTrainer.i: src/RLTrainer.cpp.i
.PHONY : src/RLTrainer.i

# target to preprocess a source file
src/RLTrainer.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CartPoleRL.dir/build.make CMakeFiles/CartPoleRL.dir/src/RLTrainer.cpp.i
.PHONY : src/RLTrainer.cpp.i

src/RLTrainer.s: src/RLTrainer.cpp.s
.PHONY : src/RLTrainer.s

# target to generate assembly for a file
src/RLTrainer.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CartPoleRL.dir/build.make CMakeFiles/CartPoleRL.dir/src/RLTrainer.cpp.s
.PHONY : src/RLTrainer.cpp.s

src/Renderer.o: src/Renderer.cpp.o
.PHONY : src/Renderer.o

# target to build an object file
src/Renderer.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CartPoleRL.dir/build.make CMakeFiles/CartPoleRL.dir/src/Renderer.cpp.o
.PHONY : src/Renderer.cpp.o

src/Renderer.i: src/Renderer.cpp.i
.PHONY : src/Renderer.i

# target to preprocess a source file
src/Renderer.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CartPoleRL.dir/build.make CMakeFiles/CartPoleRL.dir/src/Renderer.cpp.i
.PHONY : src/Renderer.cpp.i

src/Renderer.s: src/Renderer.cpp.s
.PHONY : src/Renderer.s

# target to generate assembly for a file
src/Renderer.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CartPoleRL.dir/build.make CMakeFiles/CartPoleRL.dir/src/Renderer.cpp.s
.PHONY : src/Renderer.cpp.s

src/main.o: src/main.cpp.o
.PHONY : src/main.o

# target to build an object file
src/main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CartPoleRL.dir/build.make CMakeFiles/CartPoleRL.dir/src/main.cpp.o
.PHONY : src/main.cpp.o

src/main.i: src/main.cpp.i
.PHONY : src/main.i

# target to preprocess a source file
src/main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CartPoleRL.dir/build.make CMakeFiles/CartPoleRL.dir/src/main.cpp.i
.PHONY : src/main.cpp.i

src/main.s: src/main.cpp.s
.PHONY : src/main.s

# target to generate assembly for a file
src/main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CartPoleRL.dir/build.make CMakeFiles/CartPoleRL.dir/src/main.cpp.s
.PHONY : src/main.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... CartPoleRL"
	@echo "... src/CartPoleSimulation.o"
	@echo "... src/CartPoleSimulation.i"
	@echo "... src/CartPoleSimulation.s"
	@echo "... src/PhysicsSystem.o"
	@echo "... src/PhysicsSystem.i"
	@echo "... src/PhysicsSystem.s"
	@echo "... src/RLTrainer.o"
	@echo "... src/RLTrainer.i"
	@echo "... src/RLTrainer.s"
	@echo "... src/Renderer.o"
	@echo "... src/Renderer.i"
	@echo "... src/Renderer.s"
	@echo "... src/main.o"
	@echo "... src/main.i"
	@echo "... src/main.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

