# CMake generated Testfile for 
# Source directory: /home/particle/Documents/DS2_Final_Project/mujoco/test/plugin/elasticity
# Build directory: /home/particle/Documents/DS2_Final_Project/test/plugin/elasticity
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test(ElasticityTest.FlexCompatibility "/home/particle/Documents/DS2_Final_Project/bin/elasticity_test" "--gtest_filter=ElasticityTest.FlexCompatibility")
set_tests_properties(ElasticityTest.FlexCompatibility PROPERTIES  ENVIRONMENT "MUJOCO_PLUGIN_DIR=/home/particle/Documents/DS2_Final_Project/lib" WORKING_DIRECTORY "/home/particle/Documents/DS2_Final_Project/mujoco/test" _BACKTRACE_TRIPLES "/usr/share/cmake-3.22/Modules/GoogleTest.cmake;400;add_test;/home/particle/Documents/DS2_Final_Project/mujoco/test/CMakeLists.txt;37;gtest_add_tests;/home/particle/Documents/DS2_Final_Project/mujoco/test/plugin/elasticity/CMakeLists.txt;15;mujoco_test;/home/particle/Documents/DS2_Final_Project/mujoco/test/plugin/elasticity/CMakeLists.txt;0;")
add_test(ElasticityTest.ElasticEnergyShell "/home/particle/Documents/DS2_Final_Project/bin/elasticity_test" "--gtest_filter=ElasticityTest.ElasticEnergyShell")
set_tests_properties(ElasticityTest.ElasticEnergyShell PROPERTIES  ENVIRONMENT "MUJOCO_PLUGIN_DIR=/home/particle/Documents/DS2_Final_Project/lib" WORKING_DIRECTORY "/home/particle/Documents/DS2_Final_Project/mujoco/test" _BACKTRACE_TRIPLES "/usr/share/cmake-3.22/Modules/GoogleTest.cmake;400;add_test;/home/particle/Documents/DS2_Final_Project/mujoco/test/CMakeLists.txt;37;gtest_add_tests;/home/particle/Documents/DS2_Final_Project/mujoco/test/plugin/elasticity/CMakeLists.txt;15;mujoco_test;/home/particle/Documents/DS2_Final_Project/mujoco/test/plugin/elasticity/CMakeLists.txt;0;")
add_test(PluginTest.ElasticEnergyMembrane "/home/particle/Documents/DS2_Final_Project/bin/elasticity_test" "--gtest_filter=PluginTest.ElasticEnergyMembrane")
set_tests_properties(PluginTest.ElasticEnergyMembrane PROPERTIES  ENVIRONMENT "MUJOCO_PLUGIN_DIR=/home/particle/Documents/DS2_Final_Project/lib" WORKING_DIRECTORY "/home/particle/Documents/DS2_Final_Project/mujoco/test" _BACKTRACE_TRIPLES "/usr/share/cmake-3.22/Modules/GoogleTest.cmake;400;add_test;/home/particle/Documents/DS2_Final_Project/mujoco/test/CMakeLists.txt;37;gtest_add_tests;/home/particle/Documents/DS2_Final_Project/mujoco/test/plugin/elasticity/CMakeLists.txt;15;mujoco_test;/home/particle/Documents/DS2_Final_Project/mujoco/test/plugin/elasticity/CMakeLists.txt;0;")
add_test(ElasticityTest.InvalidThickness "/home/particle/Documents/DS2_Final_Project/bin/elasticity_test" "--gtest_filter=ElasticityTest.InvalidThickness")
set_tests_properties(ElasticityTest.InvalidThickness PROPERTIES  ENVIRONMENT "MUJOCO_PLUGIN_DIR=/home/particle/Documents/DS2_Final_Project/lib" WORKING_DIRECTORY "/home/particle/Documents/DS2_Final_Project/mujoco/test" _BACKTRACE_TRIPLES "/usr/share/cmake-3.22/Modules/GoogleTest.cmake;400;add_test;/home/particle/Documents/DS2_Final_Project/mujoco/test/CMakeLists.txt;37;gtest_add_tests;/home/particle/Documents/DS2_Final_Project/mujoco/test/plugin/elasticity/CMakeLists.txt;15;mujoco_test;/home/particle/Documents/DS2_Final_Project/mujoco/test/plugin/elasticity/CMakeLists.txt;0;")
add_test(ElasticityTest.ElasticEnergySolid "/home/particle/Documents/DS2_Final_Project/bin/elasticity_test" "--gtest_filter=ElasticityTest.ElasticEnergySolid")
set_tests_properties(ElasticityTest.ElasticEnergySolid PROPERTIES  ENVIRONMENT "MUJOCO_PLUGIN_DIR=/home/particle/Documents/DS2_Final_Project/lib" WORKING_DIRECTORY "/home/particle/Documents/DS2_Final_Project/mujoco/test" _BACKTRACE_TRIPLES "/usr/share/cmake-3.22/Modules/GoogleTest.cmake;400;add_test;/home/particle/Documents/DS2_Final_Project/mujoco/test/CMakeLists.txt;37;gtest_add_tests;/home/particle/Documents/DS2_Final_Project/mujoco/test/plugin/elasticity/CMakeLists.txt;15;mujoco_test;/home/particle/Documents/DS2_Final_Project/mujoco/test/plugin/elasticity/CMakeLists.txt;0;")
add_test(ElasticityTest.CantileverIntoCircle "/home/particle/Documents/DS2_Final_Project/bin/elasticity_test" "--gtest_filter=ElasticityTest.CantileverIntoCircle")
set_tests_properties(ElasticityTest.CantileverIntoCircle PROPERTIES  ENVIRONMENT "MUJOCO_PLUGIN_DIR=/home/particle/Documents/DS2_Final_Project/lib" WORKING_DIRECTORY "/home/particle/Documents/DS2_Final_Project/mujoco/test" _BACKTRACE_TRIPLES "/usr/share/cmake-3.22/Modules/GoogleTest.cmake;400;add_test;/home/particle/Documents/DS2_Final_Project/mujoco/test/CMakeLists.txt;37;gtest_add_tests;/home/particle/Documents/DS2_Final_Project/mujoco/test/plugin/elasticity/CMakeLists.txt;15;mujoco_test;/home/particle/Documents/DS2_Final_Project/mujoco/test/plugin/elasticity/CMakeLists.txt;0;")
add_test(ElasticityTest.InvalidTxtAttribute "/home/particle/Documents/DS2_Final_Project/bin/elasticity_test" "--gtest_filter=ElasticityTest.InvalidTxtAttribute")
set_tests_properties(ElasticityTest.InvalidTxtAttribute PROPERTIES  ENVIRONMENT "MUJOCO_PLUGIN_DIR=/home/particle/Documents/DS2_Final_Project/lib" WORKING_DIRECTORY "/home/particle/Documents/DS2_Final_Project/mujoco/test" _BACKTRACE_TRIPLES "/usr/share/cmake-3.22/Modules/GoogleTest.cmake;400;add_test;/home/particle/Documents/DS2_Final_Project/mujoco/test/CMakeLists.txt;37;gtest_add_tests;/home/particle/Documents/DS2_Final_Project/mujoco/test/plugin/elasticity/CMakeLists.txt;15;mujoco_test;/home/particle/Documents/DS2_Final_Project/mujoco/test/plugin/elasticity/CMakeLists.txt;0;")
add_test(ElasticityTest.InvalidMixedAttribute "/home/particle/Documents/DS2_Final_Project/bin/elasticity_test" "--gtest_filter=ElasticityTest.InvalidMixedAttribute")
set_tests_properties(ElasticityTest.InvalidMixedAttribute PROPERTIES  ENVIRONMENT "MUJOCO_PLUGIN_DIR=/home/particle/Documents/DS2_Final_Project/lib" WORKING_DIRECTORY "/home/particle/Documents/DS2_Final_Project/mujoco/test" _BACKTRACE_TRIPLES "/usr/share/cmake-3.22/Modules/GoogleTest.cmake;400;add_test;/home/particle/Documents/DS2_Final_Project/mujoco/test/CMakeLists.txt;37;gtest_add_tests;/home/particle/Documents/DS2_Final_Project/mujoco/test/plugin/elasticity/CMakeLists.txt;15;mujoco_test;/home/particle/Documents/DS2_Final_Project/mujoco/test/plugin/elasticity/CMakeLists.txt;0;")
add_test(ElasticityTest.ValidAttributes "/home/particle/Documents/DS2_Final_Project/bin/elasticity_test" "--gtest_filter=ElasticityTest.ValidAttributes")
set_tests_properties(ElasticityTest.ValidAttributes PROPERTIES  ENVIRONMENT "MUJOCO_PLUGIN_DIR=/home/particle/Documents/DS2_Final_Project/lib" WORKING_DIRECTORY "/home/particle/Documents/DS2_Final_Project/mujoco/test" _BACKTRACE_TRIPLES "/usr/share/cmake-3.22/Modules/GoogleTest.cmake;400;add_test;/home/particle/Documents/DS2_Final_Project/mujoco/test/CMakeLists.txt;37;gtest_add_tests;/home/particle/Documents/DS2_Final_Project/mujoco/test/plugin/elasticity/CMakeLists.txt;15;mujoco_test;/home/particle/Documents/DS2_Final_Project/mujoco/test/plugin/elasticity/CMakeLists.txt;0;")
